export const LightColors = {
    backgroundColor: "#FFFFFF",
    btnColor: "#FF7622",
    lightGrey: "#646982",
    InputBox: "#F0F5FA",
    black: "#121223",
    white: "#FFFFFF",
    searchBar: "#d0d4d7",
    gray: "grey",
    cancel: "red",
    success: "#059C6A",
    semiBlack: "#181C2E",
    sideBarIcon: "#ECF0F4",
    whiteIcon: "#FFF",
    lightWhite: "#F5F5F5",
    BlackIcon: "#000",
    subtitleColor: "#32343E",
    backgroundColorBlack: "#121223",
    couponGradStart: "#FFD200",
    couponGradMiddle: "#FF9F00",
    couponGradEnd: "#FF6100",
    couponCloseBg: "#FFE08A",
    couponCloseText: "#FF7A00",
    couponBtnBg: "#E05300",
    couponTitleSize: 34,
    couponCodeSize: 26,
    couponDescSize: 16,
    zomatoRed: "#E23744",
    zomatoRedLight: "#FFF0F2",
    zomatoInactive: "#5A5A5A",
    zomatoBg: "#FFFFFF",
};

export const DarkColors = {
    ...LightColors,
    backgroundColor: "#121223",
    lightGrey: "#9CA3AF",
    InputBox: "#1E293B",
    black: "#FFFFFF",
    white: "#121223",
    searchBar: "#1E293B",
    gray: "#9CA3AF",
    semiBlack: "#FFFFFF",
    sideBarIcon: "#1E293B",
    lightWhite: "#1C1C1E",
    BlackIcon: "#FFF",
    subtitleColor: "#D1D5DB",
    backgroundColorBlack: "#121223", // Keep it dark as the Cart screen uses this background
    zomatoRedLight: "#3A1E20",
    zomatoInactive: "#9CA3AF",
    zomatoBg: "#1C1C1E",
};

export const Colors = LightColors;